### ISSUE TITLE
standardize nypl_items.csv

### ISSUE THREAD

**Issue by gcdf** [DHRI-Curriculum/curriculum#2]
Porting this issue here mostly as yet another place to link to the gcdf github account, but also 'cause this is a thing that really probably shouldn't fall off the todo list.

**Comment by kallewesterling** [comment]
@gcdf (not sure whether this was created by, for instance @lmrhody or @smythp) - but I wanted to follow up on this open issue. Not sure if the issue concerns ``standardize nypl_items.csv`` or ``link to the gcdf github account`` but I would be happy to address either issue as long as I know what it concerns?

**Comment by smythp** [comment]
Looks like was created by Hannah. Not sure about it, might just close for now.

**Comment by kallewesterling** [comment]
Thanks!
