### ISSUE TITLE
organization

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/curriculum#3]
Thanks so much for putting this together Patrick! I think one of the things that we mentioned when we got the feedback where students were asking for a running glossary was that the introduction of the terms would go in the order in which we've presented them in the tutorials. I know everyone is going to present them in a slightly different order, but it seems to me like it would make sense at leas for the major sections to be in the order that we progress through the curriculum, so I would recommend moving the Git section after the command line and ordering the remaining sections along with the institute order of workshops.

**Comment by smythp** [comment]
OK, Just reordered it. I'm going to pull this out and give it a repo for greater findability. Everything else is in the repos so I don't want to confuse anyone.
